# English Word Frequency

English word frequency

Data from: https://www.kaggle.com/rtatman/english-word-frequency

In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

# Import
df = pd.read_csv(Path('./data/unigram_freq.csv'))

# Head
df.head()

  word        count
0  the  23135851162
1   of  13151942776
2  and  12997637966
3   to  12136980858
4    a   9081174698

## Top 100 - used english words

In [32]:
dataset = df.loc[~df['word'].isin(['c', 'e', 's', 'x', 'n', 'b', 't', 'd', 'm', 'r', 'p', 'f', 'l', 'w', 'o', 'g', 'h', 'v', 'k', 'y', 'j', 'u', 'q', 'z'])]
dataset = dataset.sort_values(by='count', ascending=False)

dataset.reset_index()

dataset = dataset[:100]


print("Position: Word (Count)")

i = 0
for index, data in dataset.iterrows():
    word, count = data
    i = i + 1
    print(i,": ", word, " (", count, ")")

Position: Word (Count)
1 :  the  ( 23135851162 )
2 :  of  ( 13151942776 )
3 :  and  ( 12997637966 )
4 :  to  ( 12136980858 )
5 :  a  ( 9081174698 )
6 :  in  ( 8469404971 )
7 :  for  ( 5933321709 )
8 :  is  ( 4705743816 )
9 :  on  ( 3750423199 )
10 :  that  ( 3400031103 )
11 :  by  ( 3350048871 )
12 :  this  ( 3228469771 )
13 :  with  ( 3183110675 )
14 :  i  ( 3086225277 )
15 :  you  ( 2996181025 )
16 :  it  ( 2813163874 )
17 :  not  ( 2633487141 )
18 :  or  ( 2590739907 )
19 :  be  ( 2398724162 )
20 :  are  ( 2393614870 )
21 :  from  ( 2275595356 )
22 :  at  ( 2272272772 )
23 :  as  ( 2247431740 )
24 :  your  ( 2062066547 )
25 :  all  ( 2022459848 )
26 :  have  ( 1564202750 )
27 :  new  ( 1551258643 )
28 :  more  ( 1544771673 )
29 :  an  ( 1518266684 )
30 :  was  ( 1483428678 )
31 :  we  ( 1390661912 )
32 :  will  ( 1356293641 )
33 :  home  ( 1276852170 )
34 :  can  ( 1242323499 )
35 :  us  ( 1229112622 )
36 :  about  ( 1226734006 )
37 :  if  ( 1134987907 )
38 :  page  ( 1082121730 )
39 :  my  ( 1059793441 )
40 :  has  ( 1046319984 )
41 :  search  ( 1024093118 )
42 :  free  ( 1014107316 )
43 :  but  ( 999899654 )
44 :  our  ( 998757982 )
45 :  one  ( 993536631 )
46 :  other  ( 978481319 )
47 :  do  ( 950751722 )
48 :  no  ( 937112320 )
49 :  information  ( 932594387 )
50 :  time  ( 908705570 )
51 :  they  ( 883223816 )
52 :  site  ( 844310242 )
53 :  he  ( 842847219 )
54 :  up  ( 829969374 )
55 :  may  ( 827822032 )
56 :  what  ( 812395582 )
57 :  which  ( 810514085 )
58 :  their  ( 782849411 )
59 :  news  ( 755424983 )
60 :  out  ( 741601852 )
61 :  use  ( 719980257 )
62 :  any  ( 710741293 )
63 :  there  ( 701170205 )
64 :  see  ( 681410380 )
65 :  only  ( 661844114 )
66 :  so  ( 661809559 )
67 :  his  ( 660177731 )
68 :  when  ( 650621178 )
69 :  contact  ( 645824184 )
70 :  here  ( 639711198 )
71 :  business  ( 637134177 )
72 :  who  ( 630927278 )
73 :  web  ( 619571575 )
74 :  also  ( 616829742 )
75 :  now  ( 611387736 )
76 :  help  ( 611054034 )
77 :  get  ( 605984508 )
78 :  pm  ( 604577485 )
79 :  view  ( 602279334 )
80 :  online  ( 601317059 )
81 :  first  ( 578161543 )
82 :  am  ( 576436203 )
83 :  been  ( 575019382 )
84 :  would  ( 572644147 )
85 :  how  ( 571848080 )
86 :  were  ( 570699558 )
87 :  me  ( 566617666 )
88 :  services  ( 562206804 )
89 :  some  ( 548829454 )
90 :  these  ( 541003982 )
91 :  click  ( 536746424 )
92 :  its  ( 525627757 )
93 :  like  ( 520585287 )
94 :  service  ( 519537222 )
95 :  than  ( 502609275 )
96 :  find  ( 502043038 )
97 :  price  ( 501651226 )
98 :  date  ( 488967374 )
99 :  back  ( 488024109 )
100 :  top  ( 484213771 )